name: Decision Trees Workflow

on:
  pull_request:
    paths:
      - "decision-trees/**"
      - "requirements.txt"
    branches:
      - main

jobs:
  decision_trees:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./

      - name: Run scripts
        run: |
          python /decision-trees/mini_auto_grader.py
          python /decision-trees/unit_tests.py
          python /decision-trees/plot_learning_curves.py
          python /decision-trees/tune_random_forest.py
        working-directory: ./
