name: Build and Cache Dependencies

on:
  push:
    paths:
      - "requirements.txt"
    branches:
      - main

jobs:
  build_and_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda
        with:
          python-version: anaconda3-2023.07-0

      - name: Create and activate Conda environment
        run: |
          conda env create -f environment.yml
          conda activate myenv
        working-directory: ./

      - name: Cache Conda environments
        uses: actions/cache@v2
        with:
          path: ~/.conda/pkgs
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }} # Cache based on environment.yml file

      - name: Upload dependencies as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my_dependencies
          path: ./
